SELECT E.ENAME FROM EMP E , DEPT D ,( SELECT * FROM LOC ) L 
WHERE E.DEPTNO = D.DEPTNO AND L.LOCNO = D.LOCNO;

SELECT E.ENAME FROM AAA E , BBB D ,( SELECT * FROM LOC ) L
WHERE E.DEPTNO = D.DEPTNO AND L.LOCNO = D.LOCNO;